"""Nullable contestant_id columns in matches

Revision ID: 087b382375c2
Revises: 2148310d87d2
Create Date: 2022-09-15 18:11:59.697759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087b382375c2'
down_revision = '2148310d87d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches') as batch_op:
        batch_op.alter_column('first_contestant_id', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('second_contestant_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches') as batch_op:
        batch_op.alter_column('first_contestant_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('second_contestant_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###
