"""Add tournaments

Revision ID: 2148310d87d2
Revises: 
Create Date: 2022-08-29 17:41:30.595960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2148310d87d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', [sa.text('lower(email)')], unique=True)
    op.create_index('ix_users_username', 'users', [sa.text('lower(username)')], unique=True)
    op.create_table('contestants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('video_id', sa.String(length=16), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tournament_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_tournament_id'], ['user_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('first_contestant_id', sa.Integer(), nullable=False),
    sa.Column('second_contestant_id', sa.Integer(), nullable=False),
    sa.Column('victor_id', sa.Integer(), nullable=True),
    sa.Column('next_round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_contestant_id'], ['contestants.id'], ),
    sa.ForeignKeyConstraint(['next_round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['second_contestant_id'], ['contestants.id'], ),
    sa.ForeignKeyConstraint(['victor_id'], ['contestants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_contestants',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('round_id', 'contestant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_contestants')
    op.drop_table('matches')
    op.drop_table('rounds')
    op.drop_table('user_tournaments')
    op.drop_table('roles')
    op.drop_table('contestants')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
