"""contestants_bad_video

Revision ID: 4e544c5dfedd
Revises: fcdcf249b6e3
Create Date: 2023-01-19 15:49:25.520371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e544c5dfedd'
down_revision = 'fcdcf249b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('bad_video', sa.BOOLEAN(), nullable=True))
    op.execute("Update contestants set bad_video = false;")
    with op.batch_alter_table('contestants') as batch_op:
        batch_op.alter_column('bad_video', existing_type=sa.BOOLEAN, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contestants', 'bad_video')
    # ### end Alembic commands ###
