"""Allow longer YouTube video titles

Revision ID: fcdcf249b6e3
Revises: 087b382375c2
Create Date: 2022-10-18 16:35:06.978095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdcf249b6e3'
down_revision = '087b382375c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestants') as batch_op:
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=80), type_=sa.String(length=127))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestants') as batch_op:
        batch_op.alter_column('name', _type=sa.VARCHAR(length=80), existing_type=sa.String(length=127))
    # ### end Alembic commands ###
